import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav_bar from "./components/nav_bar";
import API from "./api";
import Weather from "./weather";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lottery",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen bg-white text-black`}
      >
        <Nav_bar />
        <API />
        {children}
        <Weather />
      </body>
    </html>
  );
}
